<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Secret;
use Doctrine\ORM\EntityRepository;

/**
 * SecretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretRepository extends EntityRepository
{
    /**
     * @param $id
     * @return Secret|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findActiveSecret($id)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->select('s')
            ->where('s.id = :id')
            ->setParameter('id', strtoupper($id))
            ->andWhere('s.expires > CURRENT_TIMESTAMP()')
            ->andWhere('s.views > 0');

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Secret $secret
     */
    public function save(Secret $secret)
    {
        $this->getEntityManager()->persist($secret);
        $this->getEntityManager()->flush();
    }

    /**
     * @return \Doctrine\ORM\EntityManager
     */
    public function getEntityManager()
    {
        return $this->_em;
    }
}
