<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Secret;
use Doctrine\ORM\EntityRepository;

/**
 * SecretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretRepository extends EntityRepository
{
    /**
     * @param Secret $secret
     */
    public function save(Secret $secret)
    {
        $this->getEntityManager()->persist($secret);
        $this->getEntityManager()->flush();
    }

    /**
     * @return \Doctrine\ORM\EntityManager
     */
    public function getEntityManager()
    {
        return $this->_em;
    }
}
