AppBundle\Entity\Secret:
    exclusion_policy: ALL
    xml_root_name: secret
    properties:
        secret:
            expose: true
            type: string
            since_version: 1.0
        views:
            expose: true
            type: integer
            since_version: 1.0
        expires:
            expose: true
            since_version: 1.0
    relations:
        -
            rel: self
            href:
                route: get_secret
                parameters:
                    id: expr(object.getId())
                absolute: true